version: '3.8'

services:
  app:
    image: 'demo:latest'
    build:
      context: .
    container_name: app
    depends_on:
    - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/graphql
      DB_USERNAME: graphql
      DB_PASSWORD: graphql
    ports:
    - "8080:8080"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      POSTGRES_DB: graphql
      POSTGRES_USER: graphql
      POSTGRES_PASSWORD: graphql
    ports:
    - "5438:5432"