spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/graphql}
    username: ${DB_USERNAME:graphql}
    password: ${DB_PASSWORD:graphql}
  sql:
    init:
      mode: always
  graphql:
    graphiql:
      enabled: true